const rows=['A','B','C','D','E','F','G','H','J','K'];
const cols=[1,2,3,4,5,6,7,8,9,10];
const defaultSongs=[
  ['The Killers – Mr. Brightside','03:42'],['Arctic Monkeys – Do I Wanna Know','04:25'],['Queen – Don’t Stop Me Now','03:29'],['Imagine Dragons – Believer','03:24'],['The Police – Every Breath You Take','04:13'],['Coldplay – Viva La Vida','04:02'],['Nirvana – Smells Like Teen Spirit','05:01'],['U2 – Beautiful Day','04:08']
].map((x,i)=>({id:'song'+(i+1),name:x[0],duration:x[1],type:'song',blobKey:null}));
const defaultPrizes=[
  {id:'p1',name:'Eldoradio Sticker Pack',type:'win',level:'small'},
  {id:'p2',name:'Eldoradio T-Shirt',type:'win',level:'small'},
  {id:'p3',name:'Festival Ticket',type:'win',level:'jackpot'}
];
const jingles=[
  {id:'j1',name:'Try again!',type:'lose'},
  {id:'j2',name:'Eldo Random',type:'random'},
  {id:'j3',name:'Jackpot Jingle',type:'win',level:'jackpot'}
];
const lightshows=[
  {name:'Normal',desc:'Ruhige Jukebox-Beleuchtung',glow:'rgba(237,22,140,.28)'},
  {name:'Winner',desc:'Goldene 8-Sekunden Gewinnshow',glow:'rgba(255,196,38,.28)'},
  {name:'Jackpot',desc:'Mehrfarbige 15-Sekunden Hauptshow',glow:'rgba(116,87,255,.33)'},
  {name:'Idle Pulse',desc:'Aufmerksamkeit zwischen zwei Spielen',glow:'rgba(55,177,255,.25)'}
];
const defaultState={
  campaign:{name:'Eldoradio Summer Tour 2026',description:'Summer Tour 2026 – Events & Festivals',validFrom:'2026-06-01',validTo:'2026-08-31',note:'Demo für Eldoradio Luxemburg',winChance:20,maxWins:50,maxJackpots:3,jackpotGap:5},
  songs:defaultSongs,prizes:defaultPrizes,
  stats:{games:1284,songs:1237,wins:47,jackpots:2,last:'vor 2 Minuten',keys:{}},
  matrix:{}
};
function makeDefaultMatrix(){let m={};let si=0;rows.forEach((r,ri)=>cols.forEach((c,ci)=>{const key=r+c;let content;if((ri+ci)%9===2)content={type:'win',id:defaultPrizes[(ri+ci)%defaultPrizes.length].id};else if((ri*3+ci)%7===0)content={type:'lose',id:'j1'};else if((ri+ci*2)%11===0)content={type:'random',id:'j2'};else {content={type:'song',id:defaultSongs[si%defaultSongs.length].id};si++;}m[key]=content;}));return m}
defaultState.matrix=makeDefaultMatrix();
let state=loadState();let selectedKey=null;let currentAudio=null;
function clone(o){return JSON.parse(JSON.stringify(o))}
function loadState(){try{const s=localStorage.getItem('eldoJukeboxState');return s?Object.assign(clone(defaultState),JSON.parse(s)):clone(defaultState)}catch(e){return clone(defaultState)}}
function saveState(show=true){syncFormToState();localStorage.setItem('eldoJukeboxState',JSON.stringify(state));if(show)toast('Lokal gespeichert ✓');renderAll()}
function syncFormToState(){if(!document.getElementById('campaignName'))return;state.campaign.name=document.getElementById('campaignName').value;state.campaign.description=document.getElementById('campaignDescription').value;state.campaign.validFrom=document.getElementById('validFrom').value;state.campaign.validTo=document.getElementById('validTo').value;state.campaign.note=document.getElementById('campaignNote').value;state.campaign.winChance=+document.getElementById('winChance').value;state.campaign.maxWins=+document.getElementById('maxWins').value;state.campaign.maxJackpots=+document.getElementById('maxJackpots').value;state.campaign.jackpotGap=+document.getElementById('jackpotGap').value}
function syncStateToForm(){const c=state.campaign;campaignName.value=c.name;campaignDescription.value=c.description;validFrom.value=c.validFrom;validTo.value=c.validTo;campaignNote.value=c.note;winChance.value=c.winChance;maxWins.value=c.maxWins;maxJackpots.value=c.maxJackpots;jackpotGap.value=c.jackpotGap}
function contentByRef(ref){if(!ref)return null;if(ref.type==='song')return state.songs.find(x=>x.id===ref.id);if(ref.type==='win')return state.prizes.find(x=>x.id===ref.id);return jingles.find(x=>x.id===ref.id)||{name:ref.type,type:ref.type}}
function cellLabel(ref){const x=contentByRef(ref);if(!x)return '—';if(ref.type==='song')return '♫ Song';if(ref.type==='win')return '🎁 Gewinn';if(ref.type==='lose')return '× Niete';return '◈ Zufall'}
function renderMatrix(){const el=document.getElementById('matrix');el.innerHTML='<div></div>'+cols.map(c=>`<div class="header">${c}</div>`).join('');rows.forEach(r=>{el.insertAdjacentHTML('beforeend',`<div class="rowhead">${r}</div>`);cols.forEach(c=>{const key=r+c,ref=state.matrix[key],type=ref?.type||'empty';el.insertAdjacentHTML('beforeend',`<button class="keycell ${type} ${selectedKey===key?'selected':''}" data-key="${key}">${cellLabel(ref)}</button>`)});});el.querySelectorAll('.keycell').forEach(b=>b.onclick=()=>selectKey(b.dataset.key))}
function selectKey(key){selectedKey=key;renderMatrix();selectedKeyEl.textContent=key;const ref=state.matrix[key],x=contentByRef(ref);selectedContent.textContent=x?`${cellLabel(ref)} · ${x.name}`:'Noch kein Inhalt zugewiesen.'}
function renderAssets(){const q=(songSearch.value||'').toLowerCase();songList.innerHTML=state.songs.filter(s=>s.name.toLowerCase().includes(q)).map(s=>assetHtml(s,'♫')).join('');prizeList.innerHTML=state.prizes.map(p=>assetHtml(p,'🎁')).join('');jingleList.innerHTML=jingles.map(j=>assetHtml(j,j.type==='lose'?'×':'◈')).join('');document.querySelectorAll('.asset-item').forEach(el=>el.onclick=()=>assignAsset(el.dataset.type,el.dataset.id))}
function assetHtml(x,icon){return `<div class="asset-item" data-type="${x.type}" data-id="${x.id}"><span class="asset-icon">${icon}</span><strong>${escapeHtml(x.name)}</strong><small>${x.duration||x.level||''}</small></div>`}
function assignAsset(type,id){if(!selectedKey){toast('Zuerst eine Taste auswählen');return}state.matrix[selectedKey]={type,id};saveState(false);selectKey(selectedKey);renderAssets();toast(`${selectedKey} zugewiesen ✓`)}
function renderStats(){statGames.textContent=fmt(state.stats.games);statSongs.textContent=fmt(state.stats.songs);statWins.textContent=fmt(state.stats.wins);statJackpots.textContent=fmt(state.stats.jackpots);statLast.textContent=state.stats.last;dashGames.textContent=fmt(state.stats.games);dashWins.textContent=fmt(state.stats.wins);dashCampaign.textContent=state.campaign.name.replace('Eldoradio ','');campaignTitle.textContent=state.campaign.name;chanceValue.textContent=state.campaign.winChance+' %';chanceBig.textContent=state.campaign.winChance+'%';document.querySelector('.probability-ring').style.background=`conic-gradient(var(--pink) 0 ${state.campaign.winChance}%,#3a3e46 ${state.campaign.winChance}% 100%)`;statsGrid.innerHTML=[['Spiele',state.stats.games],['Songs',state.stats.songs],['Gewinne',state.stats.wins],['Jackpots',state.stats.jackpots]].map(x=>`<div><span>${x[0]}</span><strong>${fmt(x[1])}</strong></div>`).join('');const counts=Object.entries(state.stats.keys).sort((a,b)=>b[1]-a[1]).slice(0,12);const max=Math.max(1,...counts.map(x=>x[1]));keyChart.innerHTML=counts.length?counts.map(([k,v])=>`<div class="bar-row"><strong>${k}</strong><div class="bar"><i style="width:${v/max*100}%"></i></div><span>${v}×</span></div>`).join(''):'<p style="color:#999">Noch keine Demo-Spiele seit dem Reset.</p>'}
function renderAudioPage(){audioPageList.innerHTML=state.songs.map(s=>`<div class="table-row"><strong>♫ ${escapeHtml(s.name)}</strong><small>${s.duration||'lokale Datei'}</small><small>${s.blobKey?'Audio gespeichert':'Demo-Titel'}</small><button class="btn small" data-play="${s.id}">▶ Test</button></div>`).join('');document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>playSongById(b.dataset.play))}
function renderPrizesPage(){prizesPageList.innerHTML=state.prizes.map(p=>`<div class="table-row"><strong>🎁 ${escapeHtml(p.name)}</strong><small>${p.level==='jackpot'?'Hauptgewinn':'Gewinn'}</small><small>ID: ${p.id}</small><button class="btn small" data-remove-prize="${p.id}">Entfernen</button></div>`).join('');document.querySelectorAll('[data-remove-prize]').forEach(b=>b.onclick=()=>{state.prizes=state.prizes.filter(x=>x.id!==b.dataset.removePrize);saveState(false);renderAll()})}
function renderLights(){lightShowGrid.innerHTML=lightshows.map(s=>`<div class="show-card" style="--glow:${s.glow}"><strong>${s.name}</strong><small>${s.desc}</small></div>`).join('')}
function renderPreviewKeys(){previewKeys.innerHTML=rows.flatMap(r=>cols.map(c=>`<button class="preview-key" data-pkey="${r+c}">${r+c}</button>`)).join('');document.querySelectorAll('[data-pkey]').forEach(b=>b.onclick=()=>playKey(b.dataset.pkey))}
function renderAll(){renderMatrix();renderAssets();renderStats();renderAudioPage();renderPrizesPage();renderLights();renderPreviewKeys()}
function fmt(n){return Number(n||0).toLocaleString('de-DE')}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1800)}
function navigate(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
nav.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>navigate(n.dataset.view));document.querySelectorAll('[data-navtarget]').forEach(b=>b.onclick=()=>navigate(b.dataset.navtarget));
function openPreview(){previewModal.classList.add('open');previewModal.setAttribute('aria-hidden','false');previewKicker.textContent='WÄHL DEINEN SONG';previewResult.textContent='DRÜCKE EINE TASTE';previewSub.textContent='A1 – K10 oder direkt unten anklicken'}
function closePreviewFn(){previewModal.classList.remove('open');previewModal.setAttribute('aria-hidden','true')}
previewBtn.onclick=openPreview;heroPreviewBtn.onclick=openPreview;closePreview.onclick=closePreviewFn;previewModal.addEventListener('click',e=>{if(e.target===previewModal)closePreviewFn()});
document.addEventListener('keydown',e=>{if(!previewModal.classList.contains('open'))return;const k=e.key.toUpperCase();if(rows.includes(k)){previewModal.dataset.row=k;previewSub.textContent=`Reihe ${k} gewählt – jetzt Zahl 1–0 drücken`;return}if(previewModal.dataset.row && /^[0-9]$/.test(e.key)){const col=e.key==='0'?10:+e.key;playKey(previewModal.dataset.row+col);delete previewModal.dataset.row}})
async function playKey(key){let ref=state.matrix[key]||{type:'random',id:'j2'};let x=contentByRef(ref);state.stats.games++;state.stats.keys[key]=(state.stats.keys[key]||0)+1;state.stats.last='gerade eben';let outcome=ref.type;if(ref.type==='random'){const canWin=state.stats.wins<state.campaign.maxWins;const roll=Math.random()*100;outcome=canWin&&roll<state.campaign.winChance?'win':'song';if(outcome==='win'){const allowJackpot=state.stats.jackpots<state.campaign.maxJackpots && state.stats.games%(Math.max(1,state.campaign.jackpotGap)+1)===0;const p=allowJackpot&&Math.random()<.18?state.prizes.find(p=>p.level==='jackpot'):state.prizes.find(p=>p.level!=='jackpot');x=p||state.prizes[0];ref={type:'win',id:x?.id}}else{x=state.songs[Math.floor(Math.random()*state.songs.length)];ref={type:'song',id:x?.id}}}
if(outcome==='song'){state.stats.songs++;previewKicker.textContent=key+' · NOW PLAYING';previewResult.textContent=x?.name||'Eldoradio Song';previewSub.textContent='♫ Musik läuft';await playSongById(x?.id,true)}else if(outcome==='win'){state.stats.wins++;const jackpot=x?.level==='jackpot';if(jackpot)state.stats.jackpots++;previewKicker.textContent=jackpot?'JACKPOT!':'GEWONNEN!';previewResult.textContent=x?.name||'Eldoradio Gewinn';previewSub.textContent=jackpot?'Hauptgewinn · DMX JACKPOT SHOW':'Gewinn · DMX WINNER SHOW';triggerLights(jackpot?'jackpot':'win');playBeep(jackpot?880:660)}else if(outcome==='lose'){previewKicker.textContent=key+' · FAST!';previewResult.textContent='DIESMAL KEIN GEWINN';previewSub.textContent='Probier eine andere Auswahl';playBeep(210)}saveState(false);renderStats()}
function triggerLights(kind){lightStrip.classList.remove('win','jackpot');void lightStrip.offsetWidth;lightStrip.classList.add(kind);setTimeout(()=>lightStrip.classList.remove(kind),kind==='jackpot'?4200:3400)}
function playBeep(freq){try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.001,a.currentTime);g.gain.exponentialRampToValueAtTime(.13,a.currentTime+.03);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.45);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.5)}catch(e){}}
async function playSongById(id,silentMissing=false){const s=state.songs.find(x=>x.id===id);if(!s?.blobKey){if(!silentMissing)toast('Demo-Titel: keine Audiodatei hinterlegt');return}try{const blob=await dbGet(s.blobKey);if(!blob)return;if(currentAudio){currentAudio.pause();URL.revokeObjectURL(currentAudio.src)}currentAudio=new Audio(URL.createObjectURL(blob));currentAudio.play()}catch(e){if(!silentMissing)toast('Audio konnte nicht abgespielt werden')}}
winChance.oninput=()=>{state.campaign.winChance=+winChance.value;renderStats()};saveBtn.onclick=()=>saveState();songSearch.oninput=renderAssets;
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('tab-'+t.dataset.tab).classList.add('active')});
randomizeBtn.onclick=()=>{state.matrix=makeDefaultMatrix();saveState(false);renderAll();toast('Tasten neu verteilt')};clearMatrixBtn.onclick=()=>{if(confirm('Alle Tastenbelegungen löschen?')){state.matrix={};saveState(false);renderAll()}};
function exportConfig(){syncFormToState();const exportState=clone(state);exportState.songs=exportState.songs.map(s=>({...s,blobKey:null,note:s.blobKey?'Audiodatei lokal vorhanden – für echte Jukebox separat kopieren':''}));const blob=new Blob([JSON.stringify(exportState,null,2)],{type:'application/json'});downloadBlob(blob,'eldo-jukebox-campaign.json');toast('USB-Paket-Konfiguration exportiert')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
exportBtn.onclick=exportConfig;importBtn.onclick=()=>importInput.click();importInput.onchange=async()=>{const f=importInput.files[0];if(!f)return;try{const data=JSON.parse(await f.text());state=data;localStorage.setItem('eldoJukeboxState',JSON.stringify(state));syncStateToForm();renderAll();toast('Konfiguration importiert ✓')}catch(e){alert('Ungültige JSON-Datei')}};
duplicateBtn.onclick=()=>{syncFormToState();state.campaign.name+=' – Kopie';syncStateToForm();saveState();};factoryResetBtn.onclick=()=>{if(confirm('Demo wirklich zurücksetzen?')){state=clone(defaultState);localStorage.removeItem('eldoJukeboxState');syncStateToForm();renderAll();toast('Demo zurückgesetzt')}};resetStatsBtn.onclick=()=>{state.stats={games:0,songs:0,wins:0,jackpots:0,last:'—',keys:{}};saveState(false);renderStats();toast('Statistik zurückgesetzt')};
addPrizeBtn.onclick=()=>{const name=prompt('Name des Gewinns?');if(!name)return;const jackpot=confirm('Ist das ein Hauptgewinn / Jackpot?');state.prizes.push({id:'p'+Date.now(),name,type:'win',level:jackpot?'jackpot':'small'});saveState(false);renderAll()};
const uploadBtns=[uploadAudioBtn,audioPageUpload];uploadBtns.forEach(b=>b.onclick=()=>audioFileInput.click());audioFileInput.onchange=async()=>{for(const f of [...audioFileInput.files]){const id='song'+Date.now()+Math.random().toString(16).slice(2);const blobKey='audio:'+id;await dbPut(blobKey,f);state.songs.push({id,name:f.name.replace(/\.[^.]+$/,''),duration:'lokal',type:'song',blobKey})}saveState(false);renderAll();toast(`${audioFileInput.files.length} Audio-Datei(en) gespeichert`);audioFileInput.value=''};
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('eldoJukeboxDB',1);r.onupgradeneeded=()=>r.result.createObjectStore('audio');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbPut(k,v){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction('audio','readwrite');tx.objectStore('audio').put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function dbGet(k){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('audio').objectStore('audio').get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
syncStateToForm();renderAll();
